<?php if (!defined('APPLICATION')) exit();
// DO NOT EDIT THIS FILE
// All of the settings defined here can be overridden in the /conf/config.php file.

/* 48322 - Todd
 * 48324 - Linc
 * 67336 - Derrick
 * 79339 - Becky
 * 84758 - Ryan
 * 86932 - Patrick
 * 87253 - Francis
 */
$Configuration['Teamwork']['Workers'] = '48322,48324,67336,79339,84758,86932,87253';