<?php if (!defined('APPLICATION')) exit();
// DO NOT EDIT THIS FILE
// All of the settings defined here can be overridden in the /conf/config.php file.

/* 48322 - Todd
 * 48324 - Linc
 * 67336 - Derrick
 * 79339 - Becky
 * 84758 - Ryan
 * 86932 - Patrick
 * 90864 - Alex
 * 94042 - Stéphane
 * 81407 - Julie
 * 88840 - Matthew
 */
$Configuration['Teamwork']['Workers'] = '48324,79339,84758,86932,90864,94042';
